### ISSUE TITLE
Failed to compile the project

### ISSUE THREAD

**Issue by Stephen-lei** [SamGinzburg/VectorVisor#5]
Hello, I am trying to build the project. when I git clone the project and use `cargo build --release `, the building process with error:

`error: could not compile `cap-primitives` (lib) due to 2 previous errors`

 
 and the triggering is 

```
error[E0061]: this method takes 1 argument but 2 arguments were supplied
  --> /home/zyl/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/cap-primitives-0.25.3/src/rustix/linux/fs/set_times_impl.rs:20:25
   |
20 |             return file.set_times(
   |                         ^^^^^^^^^
21 |                 atime.map(SystemTimeSpec::into_std),
22 |                 mtime.map(SystemTimeSpec::into_std),
   |                 ----------------------------------- unexpected argument of type `Option<fs_set_times::SystemTimeSpec>`
   |
note: expected `FileTimes`, found `Option<SystemTimeSpec>`
```
I have tried `cargo update`, but still failed, I am wondering if it is my mistake or not, thanks!

**Comment by SamGinzburg** [comment]
Hi,

I just double checked on my end and everything builds fine, although I notice you are using a proxy (rsproxy.cn) to build. Can you try building with the default crates.io mirrors and see if the error still occurs? This build error could be caused by mismatched package versions in the proxy.


If the error persists beyond that, if you can report the rustc version being used that would help debug things:
```
rustc --version
```

Thanks,
Sam

**Comment by Stephen-lei** [comment]
> Hi,
> 
> I just double checked on my end and everything builds fine, although I notice you are using a proxy (rsproxy.cn) to build. Can you try building with the default crates.io mirrors and see if the error still occurs? This build error could be caused by mismatched package versions in the proxy.
> 
> If the error persists beyond that, if you can report the rustc version being used that would help debug things:
> 
> ```
> rustc --version
> ```
> 
> Thanks, Sam



> Hi,
> 
> I just double checked on my end and everything builds fine, although I notice you are using a proxy (rsproxy.cn) to build. Can you try building with the default crates.io mirrors and see if the error still occurs? This build error could be caused by mismatched package versions in the proxy.
> 
> If the error persists beyond that, if you can report the rustc version being used that would help debug things:
> 
> ```
> rustc --version
> ```
> 
> Thanks, Sam

my rustc version is :
`rustc 1.76.0 (07dca489a 2024-02-04)`
i have changed the mirror , it still go wrong, can you tell me your rustc version？

**Comment by SamGinzburg** [comment]
Thanks for providing the info! It looks like there are a lot of regressions associated with 1.76.0 in packages that VectorVisor imports!

Older versions of rust such as https://github.com/SamGinzburg/VectorVisor/blob/151cc683a0788fdd15cb2cbeb390c61df96fc9ff/benchmarks/make_image.py#L98 have been confirmed to work, so you can try building with those (they should work).


I'll investigate what the issues are and try to see if there are easy fixes to get 1.76.0 working correctly

**Comment by SamGinzburg** [comment]
Okay so as a follow-up, I pushed a ```rust-toolchain``` file, which encodes the most recent working Rust version (1.74), so it should be buildable with that.

Longer term, some refactoring needs to be done, but I don't have the time at the moment to do that work.

**Comment by Stephen-lei** [comment]
Thank you very much! when I changed the Rust version to 1.74.0, the program could be properly built and used. i will close the issue. Again, thank you very much.
